name: Sync

on: [pull_request, push]

jobs:
  quickTests:
    name: Sync Altona
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - uses: actions/checkout@v1
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Bootstrap
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        run: node_modules/.bin/lerna run build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      - name: Sync Altona
        run: yarn run cli beacon run --testnet altona
